name = "hugo-sst-lancet"
license = "MIT"
licenselink = "https://github.com/anarchivist/hugo-sst-lancet/blob/main/LICENSE"
description = "A sensible and opinionated base theme; part of set of small sharp tools."
homepage = "https://github.com/anarchivist/hugo-sst-lancet"
tags = ["minimal"]
features = ["minimal"]
min_version = "0.88.0"

[author]
  name = "Mark A. Matienzo"
  homepage = "https://matienzo.org/"
